### ISSUE TITLE
[Bug] DRG Rotation breaks after opener. oGCD skills are replaced with True Thrust 

### ISSUE THREAD

**Issue by timemage21** [PunishXIV/WrathCombo#100]
I've been testing this issue for a bit, and haven't come up with a permanent fix yet. Mainly from observation after finishing opener, around the time Wyrmwind Thrust is available in the combo oGCDs stop weaving and True Thrust becomes the default suggestion for oGCD casts. 

- It doesn't appear casting any abilities manually will reset this behavior once started, including Wyrmwind Thrust
- Other jobs tested do not experience the same behavior on my client
- This happens in both advanced and simple modes
- Restarting Wraith combo also appears to correct the behavior

I've gathered a log that includes 3 examples of different behaviors - https://www.fflogs.com/reports/xrTMJQjdKL82PWRD
- First fight is advanced mosde
- 2nd fight is simple mode
- 3rd fight is simple mode after restarting wraith combo 
[WrathDebug.txt](https://github.com/user-attachments/files/17880245/WrathDebug.txt)

**Comment by Kagekazu** [comment]
This is fixed in Pull Request #62 
So next release it will be fixed.

**Comment by Kagekazu** [comment]
> I've tested this again after updating this morning and exact same behavior appears. Reloading the addon after the game launches also still corrects the issue [WrathDebug.txt](https://github.com/user-attachments/files/17894061/WrathDebug.txt)

I cannot seem to replicate this bug then.
Can u send a video of this behavior being on 1.0.0.2?

**Comment by timemage21** [comment]
https://youtu.be/1mWWLB9GV0U

**Comment by Kagekazu** [comment]
Is it possible to screenshot ur actual settings? To make sure it's not some error in settings ^.^

**Comment by timemage21** [comment]
![ffxiv_11242024_131110_857](https://github.com/user-attachments/assets/942ba4bb-47ad-411e-be13-b6a39f58c9aa)
![ffxiv_11242024_131045_649](https://github.com/user-attachments/assets/3e00d2b3-c4cf-40d6-af64-72a555eca069)
![ffxiv_11242024_131048_496](https://github.com/user-attachments/assets/ba902ff3-1858-4e7f-a06c-c8ea7e8c21a1)
![ffxiv_11242024_131051_270](https://github.com/user-attachments/assets/1e9ac176-3448-41a5-a057-d2cd5b4a9830)
![ffxiv_11242024_131104_092](https://github.com/user-attachments/assets/f874b053-7b8b-4765-a351-b75e22291200)

I've deleted everything I could find related to sloth/wrath combo in %AppData%\Roaming\XIVLauncher\pluginConfigs as well when troubleshooting and set up configs myself.

**Comment by timemage21** [comment]
13:19:16.148 | INF | [PLUGINM] "WrathCombo" defaultState: True wantedByAnyProfile: True loadPlugin: True
13:19:16.148 | INF | [LOCALPLUGIN] Loading WrathCombo.dll
13:19:16.907 | INF | [WrathCombo] This is ECommons v2.2.0.2 (release build without forms) and WrathCombo v1.0.0.2. Hello!
13:19:21.169 | INF | [WrathCombo] Cached 1255 preset attributes.
13:19:21.181 | INF | [LOCALPLUGIN] Finished loading "WrathCombo"
13:21:05.659 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.661 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.669 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.669 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.677 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.678 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.686 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.686 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.695 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.696 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.705 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76
13:21:05.705 | ERR | [WrathCombo] Preset error
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at XIVSlothCombo.Combos.PvE.DRG.DRG_AOE_AdvancedMode.Invoke(UInt32 actionID, UInt32 lastComboMove, Single comboTime, Byte level) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Combos\PvE\DRG\DRG.cs:line 550
	   at XIVSlothCombo.CustomComboNS.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID, IGameObject targetOverride) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\CustomCombo\CustomCombo.cs:line 65
	   at XIVSlothCombo.Core.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in C:\Users\thero\Source\Repos\WrathCombo\XIVSlothCombo\Core\IconReplacer.cs:line 76


Was digging through the Dalamud Console and this is what starts to appear in there when addon starts breaking combo. Can provide more if needed

**Comment by zbee** [comment]
Fixed in 1.0.0.3 with 366c3f2, which is being pushed.
